import type { NodeCatalogItem, WorkUnitDefinition, WorkUnitKind } from './types.js';

const unitKinds: Record<string, WorkUnitKind> = {
  manualTrigger: 'deterministic',
  scheduleTrigger: 'deterministic',
  webhookTrigger: 'connector',
  transform: 'deterministic',
  condition: 'deterministic',
  wait: 'deterministic',
  httpRequest: 'connector',
  approval: 'human',
  agentLoop: 'agent',
  notification: 'consumer',
  output: 'consumer',
  code: 'deterministic',
  repositoryCheck: 'connector',
  repositoryPatch: 'connector',
  repositoryMutation: 'connector',
  repositoryBranch: 'connector',
  repositoryCommit: 'connector',
  repositoryPush: 'connector',
  repositoryPullRequest: 'connector',
  repositoryCi: 'connector',
};

export function defaultWorkUnit(type: string): WorkUnitDefinition {
  return {
    kind: unitKinds[type] ?? 'deterministic',
    version: 1,
    inputSchema: 'any',
    outputSchema: 'any',
    timeoutMs: 60_000,
    retryAttempts: 1,
  };
}

export const nodeCatalog: NodeCatalogItem[] = [
  {
    type: 'manualTrigger',
    label: 'Manual trigger',
    category: 'Triggers',
    description: 'Start a run from the dashboard or API.',
    defaultConfig: {},
  },
  {
    type: 'scheduleTrigger',
    label: 'Schedule',
    category: 'Triggers',
    description: 'Start on a declared schedule.',
    defaultConfig: { cron: '0 9 * * 1-5' },
  },
  {
    type: 'webhookTrigger',
    label: 'Webhook',
    category: 'Triggers',
    description: 'Start when an authenticated webhook arrives.',
    defaultConfig: { path: '/events/new' },
  },
  {
    type: 'transform',
    label: 'Transform data',
    category: 'Data',
    description: 'Create a structured value for downstream nodes.',
    defaultConfig: { value: 'Prepared workflow context' },
  },
  {
    type: 'code',
    label: 'Deterministic code',
    category: 'Data',
    description: 'Run a safe, deterministic built-in transformation before the next unit.',
    defaultConfig: { operation: 'uppercase', value: '' },
  },
  {
    type: 'condition',
    label: 'Condition',
    category: 'Control',
    description: 'Select true or false outgoing edges.',
    defaultConfig: { result: true },
  },
  {
    type: 'wait',
    label: 'Wait',
    category: 'Control',
    description: 'Pause for a bounded interval.',
    defaultConfig: { durationMs: 250 },
  },
  {
    type: 'httpRequest',
    label: 'HTTP request',
    category: 'Connections',
    description: 'Call an HTTP endpoint with timeout and retry-safe semantics.',
    defaultConfig: { method: 'GET', url: '' },
  },
  {
    type: 'approval',
    label: 'Human approval',
    category: 'Human',
    description: 'Pause until an operator approves the run.',
    defaultConfig: { instructions: 'Review the proposed action.' },
  },
  {
    type: 'agentLoop',
    label: 'Bounded agent loop',
    category: 'Agent',
    description: 'Run a goal-oriented loop with explicit iteration and cost bounds.',
    defaultConfig: { goal: 'Evaluate the workflow outcome', maxIterations: 3 },
  },
  {
    type: 'notification',
    label: 'Notification',
    category: 'Operations',
    description: 'Emit a notification event for operators or integrations.',
    defaultConfig: { channel: 'operations', message: 'Workflow completed' },
  },
  {
    type: 'output',
    label: 'Output',
    category: 'Data',
    description: 'Declare the workflow result.',
    defaultConfig: { value: 'success' },
  },
  {
    type: 'repositoryCheck',
    label: 'Repository check',
    category: 'Repository',
    description: 'Run one allow-listed check in the bounded run workspace.',
    defaultConfig: { command: 'npm test' },
  },
  {
    type: 'repositoryPatch',
    label: 'Capture repository patch',
    category: 'Repository',
    description: 'Capture the current run workspace diff as a content-addressed artifact.',
    defaultConfig: {},
  },
  {
    type: 'repositoryMutation',
    label: 'Apply repository mutation',
    category: 'Repository',
    description: 'Apply explicitly declared file operations inside the bounded run workspace.',
    defaultConfig: { capabilities: [], operations: [] },
  },
  {
    type: 'repositoryBranch',
    label: 'Create repository branch',
    category: 'Repository',
    description: 'Create a branch from the exact approved base revision.',
    defaultConfig: { branch: 'factory/change', baseRevision: '' },
  },
  {
    type: 'repositoryCommit',
    label: 'Commit repository patch',
    category: 'Repository',
    description: 'Commit selected changed paths in the isolated workspace.',
    defaultConfig: { message: 'Apply workflow change', paths: [] },
  },
  {
    type: 'repositoryPush',
    label: 'Push repository branch',
    category: 'Repository',
    description: 'Push a branch to an allow-listed remote.',
    defaultConfig: { remote: 'origin', branch: '' },
  },
  {
    type: 'repositoryPullRequest',
    label: 'Open pull request',
    category: 'Repository',
    description: 'Open an auditable review request from the pushed branch.',
    defaultConfig: { title: '', body: '', head: '', base: 'main', requiresApproval: true },
  },
  {
    type: 'repositoryCi',
    label: 'Observe repository CI',
    category: 'Repository',
    description: 'Poll required GitHub checks and route the terminal result.',
    defaultConfig: { ref: '', required: [], timeoutMs: 120000, intervalMs: 2000, failurePolicy: 'fail' },
  },
];

export const knownNodeTypes = new Set(nodeCatalog.map((item) => item.type));
export const triggerNodeTypes = new Set([
  'manualTrigger',
  'scheduleTrigger',
  'webhookTrigger',
]);
